apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
      name: wazuh-agent
    spec:
      hostPID: true
      hostIPC: true
      containers:
      - name: wazuh-agent
        image: duplocloud/wazuh-agent:4.7.2-r1
        livenessProbe:
          httpGet:
            path: /healz
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
        ports:
          - name: agent-http
            containerPort: 5000
            protocol: TCP
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 512Mi
        env:
        - name: JOIN_MANAGER_MASTER_HOST
          value: "siem-manager.duplotestbed.supportlogic.io"
        - name: JOIN_MANAGER_WORKER_HOST
          value: "siem-manager.duplotestbed.supportlogic.io"
        - name: JOIN_MANAGER_PROTOCOL
          value: "https"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: WAZUH_GROUPS
          value: "default"
        - name: JOIN_MANAGER_USER
          valueFrom:
           secretKeyRef:
             name: wazuh-api-cred
             key: username
        - name: JOIN_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-api-cred
              key: password
        - name: JOIN_MANAGER_API_PORT
          value: "55000"
        - name: JOIN_MANAGER_PORT
          value: "1514"
        volumeMounts:
        - mountPath: /var/run
          name: var-run
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /proc
          name: proc
        - mountPath: /etc
          name: etc
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /lib/modules
          name: modules
        - mountPath: /var/log
          name: log
        - mountPath: /var/lib
          name: var-lib
        - mountPath: /etc/passwd
          name: etc-passwd
          readOnly: true  
        - mountPath: /etc/group
          name: etc-group
          readOnly: true            
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: var-run
        hostPath:
          path: /var/run
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: etc
        hostPath:
          path: /etc
      - name: modules
        hostPath:
          path: /lib/modules
      - name: log
        hostPath:
          path: /var/log
      - name: var-lib
        hostPath:
          path: /var/lib
      - name: etc-passwd
        hostPath:
          path: /etc/passwd
      - name: etc-group
        hostPath:
          path: /etc/group          